const actionTypes = {
  LOGIN_STARTED: 'LOGIN-STARTED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  REGISTER_STARTED: 'REGISTER-STARTED',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',
}
export default actionTypes
