const actionTypes = {
  LOGIN_STARTED: 'LOGIN-STARTED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  REGISTER_STARTED: 'REGISTER-STARTED',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILED: 'REGISTER_FAILED',

  GET_LIST_BOOK_STARTED: 'GET_LIST_BOOK-STARTED',
  GET_LIST_BOOK_SUCCESS: 'GET_LIST_BOOK_SUCCESS',
  GET_LIST_BOOK_FAILED: 'GET_LIST_BOOK_FAILED',
}
export default actionTypes
