import React, { useEffect, useState } from 'react'
/** @jsxImportSource @emotion/react */
import { css, jsx, useTheme } from '@emotion/react'
import Head from 'next/head'
import Link from 'next/link'
import { Button, H1, Space, H2, H5 } from '../components'
import Layout from '../containers/Layout'
import { useDispatch, useSelector } from 'react-redux'
import { clearCart } from '../reducers/cartSlice'
import EmptyCart from '../containers/EmptyCart/EmptyCart'
export default function Payment() {
  const cart = useSelector((state) => state.cart)
  const theme = useTheme()
  const dispatch = useDispatch()
  const adress = JSON.parse(localStorage.getItem('adress'))
  var result = Object.keys(adress).map((key) => [key, adress[key]])

  console.log('result', result)
  return (
    <>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="فروشگاه کتاب">
        <Space />
        <Space />
        <Space />
        {cart.cartItems.length == 0 ? (
          <EmptyCart></EmptyCart>
        ) : (
          <>
            <div
              css={css`
                display: flex;
                background-color: ${theme.colors.secondary};
                color: ${theme.colors.white};
                justify-content: center;

                padding: 1%;
                width: 70%;
                margin: 0 auto;
                @media (max-width: 1000px) {
                  font-size: 13px;
                }
              `}
            >
              <H1>پرداخت موفقیت آمیز بود. با تشکر از خرید شما</H1>
            </div>
            <H2>فاکتور:</H2>
            <div
              css={css`
                padding: 3%;
              `}
            >
              مرسوله شما به آدرس زیر ارسال می شود:
            </div>
            <div
              css={css`
                padding: 3%;
              `}
            >
              {result.map((add) => (
                <div>{add}</div>
              ))}
            </div>
            <div
              css={css`
                display: flex;
                background-color: ${theme.colors.blue};
                color: ${theme.colors.white};
                justify-content: space-between;
                align-items: center;
                align-self: center;
                padding: 1%;
                width: 100%;
                margin: 0 auto;
                @media (max-width: 1000px) {
                  font-size: 13px;
                }
              `}
            >
              <div>
                <H5>تصویر</H5>
              </div>
              <H5>نام</H5>

              <H5>قیمت</H5>
              <div
                css={css`
                  display: flex;
                  justify-content: center;
                  align-content: center;
                  max-width: 50px;
                  max-height: 50px;
                  @media (max-width: 550px) {
                  }
                `}
              >
                <div
                  css={css`
                    margin-top: 25%;
                    @media (max-width: 1000px) {
                    }
                  `}
                >
                  <H5>تعداد</H5>
                </div>
              </div>
              <H5>مجموع </H5>
            </div>

            {cart.cartItems.map((cartItem) => (
              <div
                css={css`
                  display: flex;
                  justify-content: space-between;
                  align-items: center;
                  align-self: center;
                  padding: 1%;
                  width: 100%;
                  margin: 0 auto;
                  border-bottom: 1px solid black;
                  @media (max-width: 1000px) {
                    font-size: 13px;
                  }
                `}
                key={cartItem.id}
              >
                <div>
                  <img
                    css={css`
                      max-width: 150px;
                      max-height: 150px;
                      @media (max-width: 1000px) {
                        max-width: 80px;
                        max-height: 80px;
                      }
                    `}
                    src={cartItem.image}
                    alt=""
                    srcSet=""
                  />
                  <div
                    css={css`
                      margin-bottom: auto;
                      margin-top: auto;
                      @media (max-width: 900px) {
                        width: 80px;
                        height: 60px;
                      }
                    `}
                  ></div>
                </div>
                <H5>{cartItem.name}</H5>

                <H5>{cartItem.price} تومان</H5>
                <div
                  css={css`
                    display: flex;
                    justify-content: center;
                    align-content: center;

                    max-width: 50px;
                    max-height: 50px;
                    @media (max-width: 550px) {
                    }
                  `}
                >
                  <div
                    css={css`
                      margin-top: 25%;
                      @media (max-width: 1000px) {
                      }
                    `}
                  >
                    <H5>{cartItem.cartQuantity}</H5>
                  </div>
                </div>
                <H5>{cartItem.price * cartItem.cartQuantity} تومان</H5>
              </div>
            ))}
            <div
              css={css`
                padding: 1%;
                width: 100%;
                margin: 0 auto;
                display: flex;
              `}
            >
              <div
                css={css`
                  width: 40%;
                  margin-right: auto;

                  @media (max-width: 500px) {
                    width: 100%;
                  }
                `}
              >
                <div
                  css={css`
                    padding: 5%;
                    justify-content: space-between;
                    @media (max-width: 1000px) {
                    }
                  `}
                >
                  <div
                    css={css`
                     display:flex;
                      }
                    `}
                  >
                    {' '}
                    <H5>پرداخت شده :</H5>
                    <H5>
                      {' '}
                      {cart.cartTotalAmount + 0.09 * cart.cartTotalAmount}
                    </H5>
                  </div>
                </div>
                <Link href="/">
                  <Button sec textWhite>
                    صفحه اصلی
                  </Button>
                </Link>
              </div>
            </div>
          </>
        )}
      </Layout>
    </>
  )
}
