import React, { useState } from 'react'

import Head from 'next/head'
import LayoutAuth from '../containers/LayoutAuth/LayoutAuth'

import {
  Button,
  InputEmail,
  InputPassword,
  H1,
  Space,
  H2,
  H3,
  H4,
  H5,
  Small,
  InputText,
} from '../components'
import FormControl from '../containers/FormControl/FormControl'
import Layout from '../containers/Layout'

export default function register() {
  const [formValue, setFormValue] = useState({})
  const handleOnChange = (name, value) => {
    setFormValue({ ...formValue, [name]: value })
  }
  const handleSubmit = (event) => {
    if (event) {
      event.preventDefault()
    }
    console.log('submit', formValue)
  }
  return (
    <div>
      <Head>
        <title>login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="فروشگاه کتاب">
        <LayoutAuth>
          <Space />
          <H1 align="center">ثبت نام </H1>

          <Space />

          <form onSubmit={handleSubmit}>
            <FormControl>
              <InputText
                onChange={(value) => handleOnChange('myname', value)}
                placeholder="نام"
              />
            </FormControl>
            <FormControl>
              <InputEmail
                onChange={(value) => handleOnChange('email', value)}
                placeholder="ایمیل"
              />
            </FormControl>
            <FormControl>
              <InputPassword
                onChange={(value) => handleOnChange('password', value)}
                placeholder="کلمه عبور"
              />
            </FormControl>
            <FormControl>
              <Button type="submit">ثبت نام </Button>
            </FormControl>
          </form>
        </LayoutAuth>
      </Layout>
    </div>
  )
}
